### ISSUE TITLE
Crashes on start with any saved filters

### ISSUE THREAD

**Issue by xboxguru** [gitgiggety/plugin.video.stash#13]
If there are any saved filters in stash, the addon crashes with a note to check the log. 

My log reproducing this is here: https://paste.kodi.tv/xocorerina

Currently using stash v0.23.1

This issue began after stash updated recently and did a database migration. I suspect it's something to do with that.

**Comment by NoirAmnesiac** [comment]
I've also been having this problem. It actually started working again after I removed the filters but stopped again later.

**Comment by mrbokster** [comment]
Upgraded as well and ran into same issue. Looking at the code for the addon it seems Stash has changed the return from the findDefaultFilter call and it no longer works with this addon, the filter property is deprecated.
![image](https://github.com/gitgiggety/plugin.video.stash/assets/149881731/d1ae6733-fb5c-468d-b49d-fa26215342f1)

I sort of brute forced my way thru it and got it working locally but I have no experience working with python or graphql so it might be quite bad.
Files that needed updating was listing.py, stash_interface.py and criteron_parser.py.

Can do a PR but since im fairly sure its not the recommended solution im hesitant.

**Comment by xboxguru** [comment]
> Can do a PR but since im fairly sure its not the recommended solution im hesitant.

Please do.  I'd like to know what edits to make to get it working.  A working extension is better than a broken one!

**Comment by mrbokster** [comment]
I put up a PR but like it says in the description, this is just what made it work for me with my set of filters. Your milage may wary :)
Hopefully it works but no guarantees.

Heres the changes https://github.com/gitgiggety/plugin.video.stash/pull/14/files

**Comment by xboxguru** [comment]
Working for me!  Thanks!  Now we just need @gitgiggety to accept it.

**Comment by gitgiggety** [comment]
I have just released v0.0.8 with the fix provided by @mrbokster (so thanks again for that).
